### PR TITLE
Swap querystring for body-parser

### LINKED ISSUE #2: parsing a snippet of html does not seem to be working
I cannot parse a snippet of html using the website. Posting data (i.e., entering html in the textarea and pressing "Parse") produces this message:

"No options.node or options.html was provided and no document object could be found."

### PR DESCRIPTION
**Pull request by Zegnat**
Fixes #2.

This aligns us more with [Express’ own documentation](http://expressjs.com/en/4x/api.html#req.body) by using their bundled middleware to parse the form.

### CODE REVIEW

**Comment by Zegnat** [comment]
Updated this to be a clean merge again after the swap to a different microformats parser. Also found out that Express actually bundles a form parser, so I dropped the need for an external dependency completely.

**Comment by gRegorLove** [comment]
@Zegnat Is this ready to merge or pending reviewers? cc @jalcine

**Review by aimee-gm — APPROVED** [review]

**Comment by aimee-gm** [comment]
@gRegorLove just tested this and looks to be working :+1: It should be good to merge

**Comment by Zegnat** [comment]
Somehow missed your comment, @gRegorLove! Apologies!

This has been ready to merge IMO. But thanks for confirming it works @aimee-gm!

(I do not have write access on this repo, else I would have opted to merge it myself.)

**Pull request merged**
